name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.4'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --split-per-abi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: finagentix-apk
        path: build/app/outputs/flutter-apk/app-*-release.apk